#ifndef CONFIG_HPP
#define CONFIG_HPP

#define DEFAULT_SSID "esp-rfid"

// should be firmwar_1.bin on the server
#define TFTP_IMAGE_FILENAME "esp-rfid.bin"

#define MAX_AP_DURATION 60

#define ALTERNATE_PUSH_PIN 0
#define PLAYPAUSE_PUSH_PIN 2
#define GREEN_LED_PIN 4
#define RED_LED_PIN 5

#define ROTARY_B 12
#define ROTARY_C 13
#define ROTARY_A 14

#define NEXT_PUSH_PIN 15



#define BUTTON_PRESSED_DELAY 100

#define UP_TAG "AF00AF00AC"
#define DOWN_TAG "AF00AF00AD"
#define NEXT_TAG "AF00AF00AE"
#define PAUSE_TAG "AF00AF00AF"

#define ALTERNATE_TAG "AF00AF00BA"
#define UP_ALTERNATE_TAG "AF00AF00BB"
#define DOWN_ALTERNATE_TAG "AF00AF00BC"
#define NEXT_ALTERNATE_TAG "AF00AF00BD"
#define PAUSE_ALTERNATE_TAG "AF00AF00BD"

#define RAW_TCP
#endif